/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 seperate.glb 
*/

import { useGLTF } from '@react-three/drei'

export default function CarRdoor(props) {
  const { nodes, materials } = useGLTF('/carCar/sport_car/seperate.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01} >
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>


          {/* <mesh geometry={nodes.CarBody_1_Car_Paint_0003_5.geometry} material={materials.Rubber} /> */}
          {/* <mesh geometry={nodes.CarBody_2_Interior_0002_3.geometry} material={materials.Side_Mirrors} /> */}
          <mesh rotateY={Math.PI} geometry={nodes.CarBody_2_Interior_0002_4.geometry} material={materials.Windows} />
          <mesh geometry={nodes.CarBody_2_Interior_0002_2.geometry} material={materials.Car_Paint} />
          <mesh geometry={nodes.CarBody_2_Interior_0002_1.geometry} material={materials.Interior} />
        </group>

        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.CarBody_2_Interior_0002_3.geometry} material={materials.Side_Mirrors} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/carCar/sport_car/seperate.glb')
