/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { Html, Mask, useMask } from '@react-three/drei'
import { useLayoutEffect } from 'react'

export default function Scene({ ...props }) {
    const { nodes, materials } = useSpline('https://prod.spline.design/51Ri4Eceg2OpQnva/scene.splinecode')
    const stencil = useMask(1, true)
    useLayoutEffect(() => {
        // console.log(nodes)
        Object.values(nodes).forEach(
            (node) => {
                if (!node) return node
                if (node.material) {
                    if ((node.name as string).startsWith(
                        'hand'
                    )) {
                        Object.assign(node.material, stencil)
                    }
                }
                return node
            })
    })
    return (
        <>
            <group {...props} dispose={null}
                position={[0 - 140, 0 - 60, 0]}
                scale={1.2}
                rotation={[0, Math.PI / 18 * 1, Math.PI / 18 * 1]}
            >
                <mesh
                    name="handl"
                    geometry={nodes.handl.geometry}
                    material={materials.skin}
                    castShadow
                    receiveShadow
                    position={[-87.42, -145.16, -109.79]}
                    rotation={[0, 0, -0.59]}
                    scale={[-2.3, 2.3, 2.3]}
                />

            </group>
            <Mask id={1} colorWrite={false} depthWrite={false} geometry={nodes.screen.geometry} receiveShadow scale={0.5} position={[0 - 50, 0, 0]}>
                {/* We can drop the HTML inside, make it a 3d-transform and portal it to the dom container above */}
                <Html className="content-embed" scale={40} transform zIndexRange={[-1, 0]}>
                    {/* <div style={{ backgroundColor: 'gray', height: '100vh', width: '100vw' }}></div> */}
                    {/* <Iconator /> */}
                </Html>
            </Mask>
        </>
    )
}
