/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 vr_exhibition_gallery_baked.glb 
Author: ida61xq (https://sketchfab.com/ida61xq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vr-exhibition-gallery-baked-ee6f3b0d9db14b62a1b3aeef04315313
Title: VR exhibition gallery baked
*/

import { useGLTF } from '@react-three/drei'
import ETwo from './ETwo'
import { Environment } from './Environment'

export default function Env() {

    return (
        <>
            <directionalLight color="red" position={[0, 0, 5]} intensity={1} />
            <ETwo />
            <Environment />
        </>
    )
}

useGLTF.preload('/vr_exhibition_gallery_baked.glb')
