/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 white_round_exhibition_gallery.glb 
Author: ChristyHsu (https://sketchfab.com/ida61xq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-round-exhibition-gallery-a443b8a0a2314a55ae5dee4dd6a151a0
Title: White round exhibition gallery
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ETwo(props) {
    const { nodes, materials } = useGLTF('/carCar/white_round_exhibition_gallery.glb')
    return (
        <group {...props} dispose={null}>
            <group scale={0.01}>
                <mesh geometry={nodes.Cylinder__0.geometry} material={materials.Cylinder__0} rotation={[-Math.PI / 2, 0, 0]} scale={[1327.45, 1327.45, 501.949]} />
                <mesh geometry={nodes.Cylinder003__0.geometry} material={materials.Cylinder__0} position={[0, 46.149, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1327.45, 1327.45, 501.949]} />
                <mesh geometry={nodes.Cylinder004__0.geometry} material={materials.Cylinder__0} position={[0, 343.929, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1940.379, 1940.379, 733.716]} />
                <mesh geometry={nodes.Cylinder005__0.geometry} material={materials.Cylinder__0} position={[0, 463.774, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[2630.109, 2630.109, 786.067]} />
                <mesh geometry={nodes.Cylinder006__0.geometry} material={materials.Cylinder__0} position={[0, 417.743, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[3366.385, 3366.385, 676.562]} />
                <mesh geometry={nodes.Torus011__0.geometry} material={materials.Cylinder__0} position={[0, 929.591, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[-1351.922, 1351.922, 1351.922]} />
                <mesh geometry={nodes.Cylinder014_Material001_0.geometry} material={materials['Material.001']} position={[0, 444.248, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-2140.547, 2140.547, 41.441]} />
                <mesh geometry={nodes.Cylinder015__0.geometry} material={materials.Cylinder__0} rotation={[-Math.PI / 2, 0, 0]} scale={[1327.45, 1327.45, 501.949]} />
                <mesh geometry={nodes.Cylinder007_Material002_0.geometry} material={materials['Material.002']} position={[0, -491.111, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1664.058, 1664.058, 181.851]} />
                <mesh geometry={nodes.Cylinder008_Material002_0.geometry} material={materials['Material.002']} position={[0, -430.178, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[2429.868, 2429.868, 103.57]} />
                <mesh geometry={nodes.Cylinder009_Material002_0.geometry} material={materials['Material.002']} position={[0, -365.182, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[3246.547, 3246.547, 103.57]} />
                <mesh geometry={nodes.Cylinder010_Material002_0.geometry} material={materials['Material.002']} position={[0, -296.993, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[4105.58, 4105.58, 103.57]} />
                <mesh geometry={nodes.Cylinder001__0.geometry} material={materials.Cylinder__0} position={[0, -213.755, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[2287.581, 2287.581, 661.655]} />
                <mesh geometry={nodes.Cylinder012_Material004_0.geometry} material={materials['Material.004']} position={[0, -213.755, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[2287.581, 2287.581, 661.655]} />
                <mesh geometry={nodes.Cylinder013__0.geometry} material={materials.Cylinder__0} position={[0, -213.755, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[2287.581, 2287.581, 661.655]} />
                <mesh geometry={nodes.Cylinder016_Material009_0.geometry} material={materials['Material.009']} position={[0, 691.037, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[-998.133, 998.133, 73.472]} />
            </group>
        </group>
    )
}

useGLTF.preload('/carCar/white_round_exhibition_gallery.glb')
